In [1]:
# When you create a new instance of EnvironmentData, it'll automatically pull historical data and initialize the database. 
from EnvironmentData import EnvironmentData 
envdt = EnvironmentData(CatsUserID = 2496, testing = True)

Gather readings: SensorReadingF: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.16s/it]
Gather readings: SensorReadingRh: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.22s/it]

In [2]:
# Detailed info is saved in the log.
with open('data/EnvironmentData.log', 'r') as file:
    print(file.read())

2024-10-09 14:25:42,720 - EnvironmentData - INFO - initialize_database
2024-10-09 14:25:42,720 - EnvironmentData - INFO - get_sensors
2024-10-09 14:25:42,720 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/cats/user/?ApiKey=XXXX&CatsUserID=XXXX
2024-10-09 14:25:43,765 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21030&ReadingType=SensorReadingF&StartUTC=1720729542&EndUTC=1728505542&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-09 14:25:45,058 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21031&ReadingType=SensorReadingF&StartUTC=1720729542&EndUTC=1728505542&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-09 14:25:46,119 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21032&ReadingType=SensorReadingF&StartUTC=1720729542&EndUTC=1728505542&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-09 14:25:47,627 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21374&ReadingType=SensorReadingRh&StartUTC=1720729542&EndUTC=1728505542&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-09 14:25:48,742 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21376&ReadingType=SensorReadingRh&StartUTC=1720729542&EndUTC=1728505542&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-09 14:25:50,024 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21378&ReadingType=SensorReadingRh&StartUTC=1720729542&EndUTC=1728505542&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-09 14:27:04,116 - EnvironmentData - INFO - initialize_database
2024-10-09 14:27:04,116 - EnvironmentData - INFO - get_sensors
2024-10-09 14:27:04,116 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/cats/user/?ApiKey=XXXX&CatsUserID=XXXX
2024-10-09 14:27:05,157 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21030&ReadingType=SensorReadingF&StartUTC=1720729624&EndUTC=1728505624&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-09 14:27:06,380 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21031&ReadingType=SensorReadingF&StartUTC=1720729624&EndUTC=1728505624&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-09 14:27:07,517 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21032&ReadingType=SensorReadingF&StartUTC=1720729624&EndUTC=1728505624&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-09 14:27:08,648 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21374&ReadingType=SensorReadingRh&StartUTC=1720729624&EndUTC=1728505624&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-09 14:27:09,826 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21376&ReadingType=SensorReadingRh&StartUTC=1720729624&EndUTC=1728505624&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-09 14:27:11,150 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21378&ReadingType=SensorReadingRh&StartUTC=1720729624&EndUTC=1728505624&MinReadingSpacing=600&RequestedOutputFormat=raw

In [3]:
# Data is now in the database.
# Columns are limited because it is historcal data. We'll expand the data once we are pulling full data. 
import polars
polars.read_parquet('data/sensors.parquet')

shape: (77_760, 4)
┌──────────┬──────────────────┬────────────────┬─────────────────┐
│ SensorID ┆ SensorReadingUTC ┆ SensorReadingF ┆ SensorReadingRh │
│ ---      ┆ ---              ┆ ---            ┆ ---             │
│ i32      ┆ i64              ┆ f64            ┆ f64             │
╞══════════╪══════════════════╪════════════════╪═════════════════╡
│ 21030    ┆ 1720729624       ┆ -310.36        ┆ null            │
│ 21030    ┆ 1720730224       ┆ -310.36        ┆ null            │
│ 21030    ┆ 1720730824       ┆ -308.92        ┆ null            │
│ 21030    ┆ 1720731424       ┆ -308.92        ┆ null            │
│ 21030    ┆ 1720732024       ┆ -310.36        ┆ null            │
│ …        ┆ …                ┆ …              ┆ …               │
│ 21378    ┆ 1728502624       ┆ null           ┆ 51.33           │
│ 21378    ┆ 1728503224       ┆ null           ┆ 51.8            │
│ 21378    ┆ 1728503824       ┆ null           ┆ 50.65           │
│ 21378    ┆ 1728504424       ┆ null           ┆ 49.6            │
│ 21378    ┆ 1728505024       ┆ null           ┆ 50.73           │
└──────────┴──────────────────┴────────────────┴─────────────────┘

In [8]:
# Get current readings. 
envdt.get_current_readings()

# Data is read into new-readings folder for consolidation at the end of the day.
import os
os.listdir('data/new-readings')

['1728505750.parquet']

In [10]:
polars.read_parquet('data/new-readings/' + os.listdir('data/new-readings')[0]).sample(5)

shape: (5, 64)
┌─────────────────────┬──────────┬────────────┬────────────┬───┬─────────────────┬───────────────────────────┬──────────────────┬─────────────┐
│ SensorName          ┆ SensorID ┆ SensorPort ┆ ServerUTC  ┆ … ┆ SensorReadingRh ┆ SensorCalibrationOffsetRh ┆ SensorEventCount ┆ SensorState │
│ ---                 ┆ ---      ┆ ---        ┆ ---        ┆   ┆ ---             ┆ ---                       ┆ ---              ┆ ---         │
│ str                 ┆ i64      ┆ i64        ┆ i64        ┆   ┆ f64             ┆ i64                       ┆ i64              ┆ str         │
╞═════════════════════╪══════════╪════════════╪════════════╪═══╪═════════════════╪═══════════════════════════╪══════════════════╪═════════════╡
│ Temp YPM 106_D0B5   ┆ 21381    ┆ 0          ┆ 1728505751 ┆ … ┆ null            ┆ null                      ┆ null             ┆ null        │
│ RH CSC K160_00cd90  ┆ 23401    ┆ 0          ┆ 1728505751 ┆ … ┆ 39.89           ┆ 0                         ┆ null             ┆ null        │
│ RH ESC 181 S_86a6b9 ┆ 28888    ┆ 0          ┆ 1728505751 ┆ … ┆ 47.0            ┆ 0                         ┆ null             ┆ null        │
│ Temp ESC 183_84925f ┆ 26844    ┆ 0          ┆ 1728505751 ┆ … ┆ null            ┆ null                      ┆ null             ┆ null        │
│ RH YPM 103_D11C     ┆ 22961    ┆ 0          ┆ 1728505751 ┆ … ┆ 50.56           ┆ 0                         ┆ null             ┆ null        │
└─────────────────────┴──────────┴────────────┴────────────┴───┴─────────────────┴───────────────────────────┴──────────────────┴─────────────┘

In [11]:
# To consolidate these into the database, run consolidate_readings.
envdt.consolidate_readings()

# Note new-readings files are gone:
print(os.listdir('data/new-readings'))

[]

In [12]:
# Now we have the full data. 
# The first rows will be missing the extra fields. 
polars.read_parquet('data/sensors.parquet').head()

shape: (5, 64)
┌─────────────┬────────────┬──────────┬──────────────────┬───┬──────────────────────────┬───────────────────────────┬──────────────────┬─────────────┐
│ DeviceDevID ┆ DeviceName ┆ SensorID ┆ SensorReadingUTC ┆ … ┆ LoraExternalPowerPresent ┆ SensorCalibrationOffsetRh ┆ SensorEventCount ┆ SensorState │
│ ---         ┆ ---        ┆ ---      ┆ ---              ┆   ┆ ---                      ┆ ---                       ┆ ---              ┆ ---         │
│ i64         ┆ str        ┆ i32      ┆ i64              ┆   ┆ i64                      ┆ i64                       ┆ i64              ┆ str         │
╞═════════════╪════════════╪══════════╪══════════════════╪═══╪══════════════════════════╪═══════════════════════════╪══════════════════╪═════════════╡
│ null        ┆ null       ┆ 21030    ┆ 1720729624       ┆ … ┆ null                     ┆ null                      ┆ null             ┆ null        │
│ null        ┆ null       ┆ 21030    ┆ 1720730224       ┆ … ┆ null                     ┆ null                      ┆ null             ┆ null        │
│ null        ┆ null       ┆ 21030    ┆ 1720730824       ┆ … ┆ null                     ┆ null                      ┆ null             ┆ null        │
│ null        ┆ null       ┆ 21030    ┆ 1720731424       ┆ … ┆ null                     ┆ null                      ┆ null             ┆ null        │
│ null        ┆ null       ┆ 21030    ┆ 1720732024       ┆ … ┆ null                     ┆ null                      ┆ null             ┆ null        │
└─────────────┴────────────┴──────────┴──────────────────┴───┴──────────────────────────┴───────────────────────────┴──────────────────┴─────────────┘

In [13]:
# Recent rows will have the full data. 
polars.read_parquet('data/sensors.parquet').tail()

shape: (5, 64)
┌─────────────┬───────────────────────────┬──────────┬──────────────────┬───┬──────────────────────────┬───────────────────────────┬──────────────────┬─────────────┐
│ DeviceDevID ┆ DeviceName                ┆ SensorID ┆ SensorReadingUTC ┆ … ┆ LoraExternalPowerPresent ┆ SensorCalibrationOffsetRh ┆ SensorEventCount ┆ SensorState │
│ ---         ┆ ---                       ┆ ---      ┆ ---              ┆   ┆ ---                      ┆ ---                       ┆ ---              ┆ ---         │
│ i64         ┆ str                       ┆ i32      ┆ i64              ┆   ┆ i64                      ┆ i64                       ┆ i64              ┆ str         │
╞═════════════╪═══════════════════════════╪══════════╪══════════════════╪═══╪══════════════════════════╪═══════════════════════════╪══════════════════╪═════════════╡
│ 15177       ┆ Yale Peabody C347 6.19.24 ┆ 30134    ┆ 1728505712       ┆ … ┆ 0                        ┆ 0                         ┆ null             ┆ null        │
│ 15178       ┆ Yale Peabody C349 6.19.24 ┆ 30135    ┆ 1728505806       ┆ … ┆ 0                        ┆ null                      ┆ null             ┆ null        │
│ 15178       ┆ Yale Peabody C349 6.19.24 ┆ 30136    ┆ 1728505806       ┆ … ┆ 0                        ┆ 0                         ┆ null             ┆ null        │
│ 15179       ┆ C352 Yale Peabody 6.19.24 ┆ 30137    ┆ 1728505628       ┆ … ┆ 0                        ┆ null                      ┆ null             ┆ null        │
│ 15179       ┆ C352 Yale Peabody 6.19.24 ┆ 30138    ┆ 1728505628       ┆ … ┆ 0                        ┆ 0                         ┆ null             ┆ null        │
└─────────────┴───────────────────────────┴──────────┴──────────────────┴───┴──────────────────────────┴───────────────────────────┴──────────────────┴─────────────┘

In [15]:
# After every consolidation, a table of readings by device is also available.
polars.read_parquet('data/devices.parquet').head()

shape: (5, 5)
┌─────────────┬─────────────────────────────────┬──────────────────┬────────────────┬─────────────────┐
│ DeviceDevID ┆ DeviceName                      ┆ SensorReadingUTC ┆ SensorReadingF ┆ SensorReadingRh │
│ ---         ┆ ---                             ┆ ---              ┆ ---            ┆ ---             │
│ i64         ┆ str                             ┆ i64              ┆ f64            ┆ f64             │
╞═════════════╪═════════════════════════════════╪══════════════════╪════════════════╪═════════════════╡
│ 11808       ┆ Basement LN2 1 YALE TWhite ETS… ┆ 1728505604       ┆ -310.9         ┆ null            │
│ 5671        ┆ Basement LN2 YalePeabody Nov 2… ┆ 1728505582       ┆ -295.4         ┆ null            │
│ 11809       ┆ Basement  -80 YALE-TWhite ETS … ┆ 1728505619       ┆ -119.6         ┆ null            │
│ 5671        ┆ Basement LN2 YalePeabody Nov 2… ┆ 1728505582       ┆ -305.3         ┆ null            │
│ 12162       ┆ Peabody TH-L Mammal Hall D444   ┆ 1728505539       ┆ 70.7           ┆ 54.61           │
└─────────────┴─────────────────────────────────┴──────────────────┴────────────────┴─────────────────┘