In [6]:
# use the EnvironmentData class to get current status.
# this also identifies all the available sensors, which we'll need to pull historical data. 
# requires setting the API key to environment variable "CORIS_API_KEY".

# this is a custom class I've built:
# if you'd like detail on it, give me your GitHub username and I'll add you to the repo.
from EnvironmentData import EnvironmentData 

api = EnvironmentData(CatsUserID = 2496)
current = api.get_current_status()
current.columns

# here are the columns that are available:

['SensorName',
 'SensorID',
 'SensorPort',
 'ServerUTC',
 'HexGatewayMac',
 'LoraHexGatewayMac',
 'LoraGatewayLastHeardUTC',
 'SensorUnplugged',
 'LinkQualityText',
 'HexMac',
 'SensorDeleted',
 'SensorDeactivated',
 'SensorReading',
 'SensorReadingUTC',
 'DeviceName',
 'DevTypeInt',
 'DeviceDevID',
 'SensorTempPref',
 'DeviceTempPref',
 'UserTempPref',
 'SensorTimeZone',
 'SensorZipcode',
 'SensorType',
 'SensorState0String',
 'SensorState1String',
 'LN2LevelADCThresh',
 'LN2LevelADCThreshCatsUserID',
 'LN2LevelADCThreshModifiedUTC',
 'DiscreteLightSensorADCThresh',
 'DiscreteLightSensorADCThreshCatsUserID',
 'DiscreteLightSensorADCThreshModifiedUTC',
 'DiscreteLightSensorOnOffLuxThreshold',
 'DiscreteLightSensorOnOffLuxThresholdCatsUserID',
 'DiscreteLightSensorOnOffLuxThresholdModifiedUTC',
 'ExpectedSensorReadingIntervalSeconds',
 'SensorReadingC',
 'SensorCalibrationOffsetC',
 'SensorReadingF',
 'SensorCalibrationOffsetF',
 'SensorCalibrationOffsetExplanationText',
 'SensorCalibrationOffsetExplanationFirstName',
 'SensorCalibrationOffsetExplanationLastName',
 'SensorCalibrationOffsetUTC',
 'LoraBatteryPresent',
 'LoraBattery_mV',
 'LoraBatteryPercentage',
 'LoraBatteryUTC',
 'LoraBatteryIsCharging',
 'LastSensorErrorValue',
 'LastSensorErrorUTC',
 'UnivID',
 'SensorSerialNumber',
 'HeatIndexRh',
 'ConjoinedRhSensorSensorReadingRh',
 'ConjoinedRhSensorSensorID',
 'ConjoinedRhSensorSensorReadingUTC',
 'SensorReadingHeatIndexF',
 'SensorReadingHeatIndexC',
 'HeatIndexWarningTier',
 'LoraExternalPowerPresent',
 'SensorReadingRh',
 'SensorCalibrationOffsetRh',
 'SensorEventCount',
 'SensorState']

In [5]:
current[0]

# here is the first row of data:

shape: (1, 64)
┌────────────────────────────────┬──────────┬────────────┬────────────┬───┬─────────────────┬───────────────────────────┬──────────────────┬─────────────┐
│ SensorName                     ┆ SensorID ┆ SensorPort ┆ ServerUTC  ┆ … ┆ SensorReadingRh ┆ SensorCalibrationOffsetRh ┆ SensorEventCount ┆ SensorState │
│ ---                            ┆ ---      ┆ ---        ┆ ---        ┆   ┆ ---             ┆ ---                       ┆ ---              ┆ ---         │
│ str                            ┆ i64      ┆ i64        ┆ i64        ┆   ┆ f64             ┆ i64                       ┆ i64              ┆ str         │
╞════════════════════════════════╪══════════╪════════════╪════════════╪═══╪═════════════════╪═══════════════════════════╪══════════════════╪═════════════╡
│ Cryo tank 1 on ETS 01AB4F (P3) ┆ 21030    ┆ 3          ┆ 1727916020 ┆ … ┆ null            ┆ null                      ┆ null             ┆ null        │
└────────────────────────────────┴──────────┴────────────┴────────────┴───┴─────────────────┴───────────────────────────┴──────────────────┴─────────────┘

In [2]:
history = api.get_historical_status(days_back = 90, testing = True)
history['Temperature']

# here is the historical Temperature:

Gather historical readings: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:23<00:00,  1.20s/it]

shape: (129_536, 3)
┌────────────┬───────────┬──────────┐
│ UTC        ┆ Reading   ┆ SensorID │
│ ---        ┆ ---       ┆ ---      │
│ i64        ┆ f32       ┆ i32      │
╞════════════╪═══════════╪══════════╡
│ 1720139996 ┆ 68.989998 ┆ 21373    │
│ 1720140596 ┆ 69.029999 ┆ 21373    │
│ 1720141196 ┆ 69.010002 ┆ 21373    │
│ 1720141796 ┆ 68.900002 ┆ 21373    │
│ 1720142396 ┆ 68.900002 ┆ 21373    │
│ …          ┆ …         ┆ …        │
│ 1727912996 ┆ 67.529999 ┆ 22964    │
│ 1727913596 ┆ 67.059998 ┆ 22964    │
│ 1727914196 ┆ 67.709999 ┆ 22964    │
│ 1727914796 ┆ 68.139999 ┆ 22964    │
│ 1727915396 ┆ 67.639999 ┆ 22964    │
└────────────┴───────────┴──────────┘

In [3]:
history['Humidity']

# and historical Humidity:

shape: (129_536, 3)
┌────────────┬───────────┬──────────┐
│ UTC        ┆ Reading   ┆ SensorID │
│ ---        ┆ ---       ┆ ---      │
│ i64        ┆ f32       ┆ i32      │
╞════════════╪═══════════╪══════════╡
│ 1720139996 ┆ 53.939999 ┆ 21374    │
│ 1720140596 ┆ 53.259998 ┆ 21374    │
│ 1720141196 ┆ 52.830002 ┆ 21374    │
│ 1720141796 ┆ 54.889999 ┆ 21374    │
│ 1720142396 ┆ 54.279999 ┆ 21374    │
│ …          ┆ …         ┆ …        │
│ 1727912996 ┆ 55.84     ┆ 22965    │
│ 1727913596 ┆ 58.73     ┆ 22965    │
│ 1727914196 ┆ 58.799999 ┆ 22965    │
│ 1727914796 ┆ 56.639999 ┆ 22965    │
│ 1727915396 ┆ 56.290001 ┆ 22965    │
└────────────┴───────────┴──────────┘

In [ ]:
# next up: create a databse using Parquet and a function that uses DuckDB to insert the current into the historical.