In [1]:
# When you create a new instance of EnvironmentData, it'll automatically pull historical data and initialize the database. 
from EnvironmentData import EnvironmentData 
api = EnvironmentData(CatsUserID = 2496, testing = True)
api.readings

Gather readings for Temperature: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.08s/it]
Gather readings for Humidity: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.06s/it]

{'Temperature': {'ReadingType': 'SensorReadingF',
  'data': [],
  'datafile': './data//Temperature-testing.parquet'},
 'Humidity': {'ReadingType': 'SensorReadingRh',
  'data': [],
  'datafile': './data//Humidity-testing.parquet'}}

In [2]:
# Detailed info is saved in the log.
with open('data/EnvironmentData.log', 'r') as file:
    print(file.read())

2024-10-07 10:17:05,823 - EnvironmentData - INFO - initialize_database
2024-10-07 10:17:05,823 - EnvironmentData - INFO - get_sensor_ids
2024-10-07 10:17:05,823 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/cats/user/?ApiKey=XXXX&CatsUserID=XXXX
2024-10-07 10:17:06,907 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21373&ReadingType=SensorReadingF&StartUTC=1720541825&EndUTC=1728317825&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-07 10:17:08,660 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21375&ReadingType=SensorReadingF&StartUTC=1720541825&EndUTC=1728317825&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-07 10:17:10,037 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21377&ReadingType=SensorReadingF&StartUTC=1720541825&EndUTC=1728317825&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-07 10:17:11,313 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21374&ReadingType=SensorReadingRh&StartUTC=1720541825&EndUTC=1728317825&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-07 10:17:12,574 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21376&ReadingType=SensorReadingRh&StartUTC=1720541825&EndUTC=1728317825&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-07 10:17:13,961 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21378&ReadingType=SensorReadingRh&StartUTC=1720541825&EndUTC=1728317825&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-07 10:17:15,113 - EnvironmentData - INFO - Initialize database for Temperature.
2024-10-07 10:28:36,295 - EnvironmentData - INFO - initialize_database
2024-10-07 10:28:36,296 - EnvironmentData - INFO - get_sensor_ids
2024-10-07 10:28:36,296 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/cats/user/?ApiKey=XXXX&CatsUserID=XXXX
2024-10-07 10:28:37,171 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21373&ReadingType=SensorReadingF&StartUTC=1720542516&EndUTC=1728318516&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-07 10:28:38,366 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21375&ReadingType=SensorReadingF&StartUTC=1720542516&EndUTC=1728318516&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-07 10:28:39,455 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21377&ReadingType=SensorReadingF&StartUTC=1720542516&EndUTC=1728318516&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-07 10:28:40,421 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21374&ReadingType=SensorReadingRh&StartUTC=1720542516&EndUTC=1728318516&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-07 10:28:41,453 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21376&ReadingType=SensorReadingRh&StartUTC=1720542516&EndUTC=1728318516&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-07 10:28:42,440 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21378&ReadingType=SensorReadingRh&StartUTC=1720542516&EndUTC=1728318516&MinReadingSpacing=600&RequestedOutputFormat=raw
2024-10-07 10:28:43,611 - EnvironmentData - INFO - Initialize database for Temperature.
2024-10-07 10:28:43,642 - EnvironmentData - INFO - Initialize database for Humidity.

In [3]:
# Data is now in the database.
import polars
polars.read_parquet('data/Humidity-testing.parquet')

shape: (38_880, 3)
┌────────────┬───────────┬──────────┐
│ UTC        ┆ Reading   ┆ SensorID │
│ ---        ┆ ---       ┆ ---      │
│ i64        ┆ f32       ┆ i32      │
╞════════════╪═══════════╪══════════╡
│ 1720542516 ┆ 52.330002 ┆ 21374    │
│ 1720543116 ┆ 52.490002 ┆ 21374    │
│ 1720543716 ┆ 52.779999 ┆ 21374    │
│ 1720544316 ┆ 52.720001 ┆ 21374    │
│ 1720544916 ┆ 52.84     ┆ 21374    │
│ …          ┆ …         ┆ …        │
│ 1728315516 ┆ 60.880001 ┆ 21378    │
│ 1728316116 ┆ 61.349998 ┆ 21378    │
│ 1728316716 ┆ 61.740002 ┆ 21378    │
│ 1728317316 ┆ 61.84     ┆ 21378    │
│ 1728317916 ┆ 61.849998 ┆ 21378    │
└────────────┴───────────┴──────────┘

In [4]:
polars.read_parquet('data/Temperature-testing.parquet')

shape: (38_880, 3)
┌────────────┬───────────┬──────────┐
│ UTC        ┆ Reading   ┆ SensorID │
│ ---        ┆ ---       ┆ ---      │
│ i64        ┆ f32       ┆ i32      │
╞════════════╪═══════════╪══════════╡
│ 1720542516 ┆ 70.519997 ┆ 21373    │
│ 1720543116 ┆ 70.339996 ┆ 21373    │
│ 1720543716 ┆ 70.540001 ┆ 21373    │
│ 1720544316 ┆ 70.360001 ┆ 21373    │
│ 1720544916 ┆ 70.650002 ┆ 21373    │
│ …          ┆ …         ┆ …        │
│ 1728315516 ┆ 70.199997 ┆ 21377    │
│ 1728316116 ┆ 70.230003 ┆ 21377    │
│ 1728316716 ┆ 70.25     ┆ 21377    │
│ 1728317316 ┆ 70.230003 ┆ 21377    │
│ 1728317916 ┆ 70.199997 ┆ 21377    │
└────────────┴───────────┴──────────┘

In [5]:
# Get current readings. 
api.get_current_readings()

# Data is read into new-readings folder for consolidation at the end of the day.
import os
os.listdir('data/new-readings')

['Humidity-1728317874.parquet',
 'Humidity-1728318523.parquet',
 'Temperature-1728317874.parquet',
 'Temperature-1728318523.parquet']

In [6]:
# To consolidate these into the database, run consolidate_readings.
api.consolidate_readings()
print(os.listdir('data/new-readings'))

[]

In [7]:
polars.read_parquet('data/Temperature-testing.parquet')

# note the increase in row count compared to above.

shape: (39_010, 3)
┌────────────┬───────────┬──────────┐
│ UTC        ┆ Reading   ┆ SensorID │
│ ---        ┆ ---       ┆ ---      │
│ i64        ┆ f32       ┆ i32      │
╞════════════╪═══════════╪══════════╡
│ 1720542516 ┆ 70.519997 ┆ 21373    │
│ 1720543116 ┆ 70.339996 ┆ 21373    │
│ 1720543716 ┆ 70.540001 ┆ 21373    │
│ 1720544316 ┆ 70.360001 ┆ 21373    │
│ 1720544916 ┆ 70.650002 ┆ 21373    │
│ …          ┆ …         ┆ …        │
│ 1728318497 ┆ 21.58     ┆ 29712    │
│ 1728318527 ┆ 21.35     ┆ 29714    │
│ 1728318511 ┆ 20.73     ┆ 30133    │
│ 1728318306 ┆ 20.129999 ┆ 30135    │
│ 1728318470 ┆ 20.84     ┆ 30137    │
└────────────┴───────────┴──────────┘