# 1 Initialize the Database

All the code related to data management is in the `EnvironmentData` class. This makes life easier - for example: we can send the CatsUserID once and it becomes a class property. Then, when we call other operations we don't have to send this information again.

When you create a new instance of `EnvironmentData` and there is no database, it will pull historical data and initialize the database.

In [1]:
# Clear prior data. 
import os, sys, shutil

# Add parent directory to Python path to import EnvironmentData.
sys.path.append(os.path.dirname(os.getcwd()))

# Get the EnvironmentData class.
from EnvironmentData import EnvironmentData 

# The project adds to existing data so we need to clear that data to get a solid test from scratch.
if os.path.exists('../data'):
    shutil.rmtree('../data')
    os.makedirs('../data')

# Initialize EnvironmentData. This will run the historical data pull.
envdt = EnvironmentData(
    #days_back = 365 * 2,
    days_back = 7,
    coris_enabled = True,
    licor_enabled = True,
    conserv_enabled = True, 
    testing = True,
    # Since we are running from the experiments/ folder, we need to tell the class to use the parent directory as home.
    home_directory = ".."
)

DEBUG: Enabled data sources: ['Coris', 'Conserv', 'LI-COR']

Gather Coris readings: SensorReadingF: 100%|███████████| 3/3 [00:05<00:00,  1.86s/it]
Gather Coris readings: SensorReadingRh: 100%|██████████| 3/3 [00:05<00:00,  1.90s/it]
Gathering Conserv historical data: 100%|██████████████| 1/1 [01:42<00:00, 102.11s/it]
Gathering LI-COR readings: 100%|███████████████████████| 4/4 [00:01<00:00,  3.10it/s]

Detailed information is saved in the log:

In [2]:
# Detailed info is saved in the log.
with open('../data/EnvironmentData.log', 'r') as file:
    for line in file.read().splitlines()[:10]:
        print(line)

2025-11-15 13:55:04,434 - EnvironmentData - INFO - Initialized Conserv client with 5 customers
2025-11-15 13:55:04,436 - EnvironmentData - INFO - Enabled data sources: ['Coris', 'Conserv', 'LI-COR']
2025-11-15 13:55:04,436 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/cats/user/?ApiKey=XXXX&CatsUserID=XXXX
2025-11-15 13:55:06,317 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21373&ReadingType=SensorReadingF&StartUTC=1762635304&EndUTC=1763240104&MinReadingSpacing=600&RequestedOutputFormat=raw
2025-11-15 13:55:08,164 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21375&ReadingType=SensorReadingF&StartUTC=1762635304&EndUTC=1763240104&MinReadingSpacing=600&RequestedOutputFormat=raw
2025-11-15 13:55:10,017 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21377&ReadingType=SensorReadingF&StartUTC=1762635304&EndUTC=1763240104&MinReadingSpacing=600&RequestedOutputFormat=raw
2025-11-15 13:55:11,890 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21374&ReadingType=SensorReadingRh&StartUTC=1762635304&EndUTC=1763240104&MinReadingSpacing=600&RequestedOutputFormat=raw
2025-11-15 13:55:13,895 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21376&ReadingType=SensorReadingRh&StartUTC=1762635304&EndUTC=1763240104&MinReadingSpacing=600&RequestedOutputFormat=raw
2025-11-15 13:55:15,758 - EnvironmentData - INFO - API call: https://cats.corismonitoring.com/api/sensor/historical/?ApiKey=XXXX&SensorID=21378&ReadingType=SensorReadingRh&StartUTC=1762635304&EndUTC=1763240104&MinReadingSpacing=600&RequestedOutputFormat=raw
2025-11-15 13:55:17,595 - EnvironmentData - INFO - initialize_database validation passed: no duplicated SensorReadingUTC per SensorID.

This saves our intermediate data to `data/sensor_readings.parquet`. 

Initially, we leave the data mostly as-is. We'll clean, add formatted dates, consolidate readings from the same device, etc. when moving to analytical steps, this preserves the source data so we can always change our mind later about how we decide to view it. 

However, at this point we are taking care to standardize the data format between different API sources. 

There are just a few columns because this is only historical data. We'll bring in current data shortly, and that will add more columns.

In [3]:
import polars
polars.read_parquet('../data/sensor_readings.parquet').filter(polars.col("Source") == "Coris").head()

shape: (5, 10)
┌──────────┬──────────┬────────┬─────────┬───┬─────────┬─────────┬─────────┬─────────┐
│ SensorRe ┆ QueryUTC ┆ Source ┆ DeviceI ┆ … ┆ SensorN ┆ SensorT ┆ SensorR ┆ SensorR │
│ adingUTC ┆ ---      ┆ ---    ┆ D       ┆   ┆ ame     ┆ ype     ┆ eadingF ┆ eadingR │
│ ---      ┆ i32      ┆ str    ┆ ---     ┆   ┆ ---     ┆ ---     ┆ ---     ┆ h       │
│ i64      ┆          ┆        ┆ str     ┆   ┆ str     ┆ str     ┆ f32     ┆ ---     │
│          ┆          ┆        ┆         ┆   ┆         ┆         ┆         ┆ f32     │
╞══════════╪══════════╪════════╪═════════╪═══╪═════════╪═════════╪═════════╪═════════╡
│ 17626353 ┆ 17632401 ┆ Coris  ┆ coris:1 ┆ … ┆ PYPM__0 ┆ Tempera ┆ 68.7900 ┆ null    │
│ 04       ┆ 06       ┆        ┆ 2162    ┆   ┆ 100104S ┆ ture    ┆ 01      ┆         │
│          ┆          ┆        ┆         ┆   ┆ ET____  ┆         ┆         ┆         │
│          ┆          ┆        ┆         ┆   ┆ Temp    ┆         ┆         ┆         │
│          ┆          ┆        ┆         ┆   ┆ YPM …   ┆         ┆         ┆         │
│ 17626359 ┆ 17632401 ┆ Coris  ┆ coris:1 ┆ … ┆ PYPM__0 ┆ Tempera ┆ 68.7900 ┆ null    │
│ 04       ┆ 06       ┆        ┆ 2162    ┆   ┆ 100104S ┆ ture    ┆ 01      ┆         │
│          ┆          ┆        ┆         ┆   ┆ ET____  ┆         ┆         ┆         │
│          ┆          ┆        ┆         ┆   ┆ Temp    ┆         ┆         ┆         │
│          ┆          ┆        ┆         ┆   ┆ YPM …   ┆         ┆         ┆         │
│ 17626365 ┆ 17632401 ┆ Coris  ┆ coris:1 ┆ … ┆ PYPM__0 ┆ Tempera ┆ 68.7200 ┆ null    │
│ 04       ┆ 06       ┆        ┆ 2162    ┆   ┆ 100104S ┆ ture    ┆ 01      ┆         │
│          ┆          ┆        ┆         ┆   ┆ ET____  ┆         ┆         ┆         │
│          ┆          ┆        ┆         ┆   ┆ Temp    ┆         ┆         ┆         │
│          ┆          ┆        ┆         ┆   ┆ YPM …   ┆         ┆         ┆         │
│ 17626371 ┆ 17632401 ┆ Coris  ┆ coris:1 ┆ … ┆ PYPM__0 ┆ Tempera ┆ 68.68   ┆ null    │
│ 04       ┆ 06       ┆        ┆ 2162    ┆   ┆ 100104S ┆ ture    ┆         ┆         │
│          ┆          ┆        ┆         ┆   ┆ ET____  ┆         ┆         ┆         │
│          ┆          ┆        ┆         ┆   ┆ Temp    ┆         ┆         ┆         │
│          ┆          ┆        ┆         ┆   ┆ YPM …   ┆         ┆         ┆         │
│ 17626377 ┆ 17632401 ┆ Coris  ┆ coris:1 ┆ … ┆ PYPM__0 ┆ Tempera ┆ 68.6699 ┆ null    │
│ 04       ┆ 06       ┆        ┆ 2162    ┆   ┆ 100104S ┆ ture    ┆ 98      ┆         │
│          ┆          ┆        ┆         ┆   ┆ ET____  ┆         ┆         ┆         │
│          ┆          ┆        ┆         ┆   ┆ Temp    ┆         ┆         ┆         │
│          ┆          ┆        ┆         ┆   ┆ YPM …   ┆         ┆         ┆         │
└──────────┴──────────┴────────┴─────────┴───┴─────────┴─────────┴─────────┴─────────┘

In [4]:
polars.read_parquet('../data/sensor_readings.parquet').filter(polars.col("Source") == "LI-COR").head()

shape: (5, 10)
┌──────────┬──────────┬────────┬─────────┬───┬─────────┬─────────┬─────────┬─────────┐
│ SensorRe ┆ QueryUTC ┆ Source ┆ DeviceI ┆ … ┆ SensorN ┆ SensorT ┆ SensorR ┆ SensorR │
│ adingUTC ┆ ---      ┆ ---    ┆ D       ┆   ┆ ame     ┆ ype     ┆ eadingF ┆ eadingR │
│ ---      ┆ i32      ┆ str    ┆ ---     ┆   ┆ ---     ┆ ---     ┆ ---     ┆ h       │
│ i64      ┆          ┆        ┆ str     ┆   ┆ str     ┆ str     ┆ f32     ┆ ---     │
│          ┆          ┆        ┆         ┆   ┆         ┆         ┆         ┆ f32     │
╞══════════╪══════════╪════════╪═════════╪═══╪═════════╪═════════╪═════════╪═════════╡
│ 17626356 ┆ 17632402 ┆ LI-COR ┆ licor:2 ┆ … ┆ null    ┆ Tempera ┆ 70.4895 ┆ null    │
│ 00       ┆ 24       ┆        ┆ 2202142 ┆   ┆         ┆ ture    ┆ 25      ┆         │
│ 17626365 ┆ 17632402 ┆ LI-COR ┆ licor:2 ┆ … ┆ null    ┆ Tempera ┆ 70.6053 ┆ null    │
│ 00       ┆ 24       ┆        ┆ 2202142 ┆   ┆         ┆ ture    ┆ 62      ┆         │
│ 17626374 ┆ 17632402 ┆ LI-COR ┆ licor:2 ┆ … ┆ null    ┆ Tempera ┆ 70.6825 ┆ null    │
│ 00       ┆ 24       ┆        ┆ 2202142 ┆   ┆         ┆ ture    ┆ 79      ┆         │
│ 17626383 ┆ 17632402 ┆ LI-COR ┆ licor:2 ┆ … ┆ null    ┆ Tempera ┆ 70.6053 ┆ null    │
│ 00       ┆ 24       ┆        ┆ 2202142 ┆   ┆         ┆ ture    ┆ 62      ┆         │
│ 17626392 ┆ 17632402 ┆ LI-COR ┆ licor:2 ┆ … ┆ null    ┆ Tempera ┆ 70.5667 ┆ null    │
│ 00       ┆ 24       ┆        ┆ 2202142 ┆   ┆         ┆ ture    ┆ 5       ┆         │
└──────────┴──────────┴────────┴─────────┴───┴─────────┴─────────┴─────────┴─────────┘

In [5]:
polars.read_parquet('../data/sensor_readings.parquet').filter(polars.col("Source") == "Conserv").head()

shape: (5, 10)
┌──────────┬─────────┬─────────┬─────────┬───┬─────────┬─────────┬─────────┬─────────┐
│ SensorRe ┆ QueryUT ┆ Source  ┆ DeviceI ┆ … ┆ SensorN ┆ SensorT ┆ SensorR ┆ SensorR │
│ adingUTC ┆ C       ┆ ---     ┆ D       ┆   ┆ ame     ┆ ype     ┆ eadingF ┆ eadingR │
│ ---      ┆ ---     ┆ str     ┆ ---     ┆   ┆ ---     ┆ ---     ┆ ---     ┆ h       │
│ i64      ┆ i32     ┆         ┆ str     ┆   ┆ str     ┆ str     ┆ f32     ┆ ---     │
│          ┆         ┆         ┆         ┆   ┆         ┆         ┆         ┆ f32     │
╞══════════╪═════════╪═════════╪═════════╪═══╪═════════╪═════════╪═════════╪═════════╡
│ 17626357 ┆ 1763240 ┆ Conserv ┆ conserv ┆ … ┆ BFAST__ ┆ Tempera ┆ 69.9079 ┆ null    │
│ 33       ┆ 118     ┆         ┆ :333:c0 ┆   ┆ BS_____ ┆ ture    ┆ 97      ┆         │
│          ┆         ┆         ┆ 09096   ┆   ┆ ______  ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ - Tempe ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ ra…     ┆         ┆         ┆         │
│ 17626366 ┆ 1763240 ┆ Conserv ┆ conserv ┆ … ┆ BFAST__ ┆ Tempera ┆ 69.8000 ┆ null    │
│ 39       ┆ 118     ┆         ┆ :333:c0 ┆   ┆ BS_____ ┆ ture    ┆ 03      ┆         │
│          ┆         ┆         ┆ 09096   ┆   ┆ ______  ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ - Tempe ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ ra…     ┆         ┆         ┆         │
│ 17626375 ┆ 1763240 ┆ Conserv ┆ conserv ┆ … ┆ BFAST__ ┆ Tempera ┆ 69.6740 ┆ null    │
│ 33       ┆ 118     ┆         ┆ :333:c0 ┆   ┆ BS_____ ┆ ture    ┆ 04      ┆         │
│          ┆         ┆         ┆ 09096   ┆   ┆ ______  ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ - Tempe ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ ra…     ┆         ┆         ┆         │
│ 17626393 ┆ 1763240 ┆ Conserv ┆ conserv ┆ … ┆ BFAST__ ┆ Tempera ┆ 69.4759 ┆ null    │
│ 33       ┆ 118     ┆         ┆ :333:c0 ┆   ┆ BS_____ ┆ ture    ┆ 98      ┆         │
│          ┆         ┆         ┆ 09096   ┆   ┆ ______  ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ - Tempe ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ ra…     ┆         ┆         ┆         │
│ 17626402 ┆ 1763240 ┆ Conserv ┆ conserv ┆ … ┆ BFAST__ ┆ Tempera ┆ 69.3499 ┆ null    │
│ 33       ┆ 118     ┆         ┆ :333:c0 ┆   ┆ BS_____ ┆ ture    ┆ 98      ┆         │
│          ┆         ┆         ┆ 09096   ┆   ┆ ______  ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ - Tempe ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ ra…     ┆         ┆         ┆         │
└──────────┴─────────┴─────────┴─────────┴───┴─────────┴─────────┴─────────┴─────────┘

# 2 Get Current Readings

Now we can start gathering and appending readings. There is a function `get_current_readings` that is run throughout the day, every 10 minutes for example. This function creates a parquet file at `data/new-readings` with the UTC as a filename. At the end of the day, all these readings will be consolidated into the database. 

Here is a sample of the readings:

In [6]:
envdt.get_current_readings()

# Data is read into new-readings folder for consolidation at the end of the day.
import os
filename = os.listdir('../data/new-readings')[0]
print(filename)
polars.read_parquet('../data/new-readings/' + filename).sample(5)

Gathering Conserv current readings: 100%|█████████████| 1/1 [01:40<00:00, 100.73s/it]

1763240224.parquet

shape: (5, 10)
┌──────────┬─────────┬─────────┬─────────┬───┬─────────┬─────────┬─────────┬─────────┐
│ SensorRe ┆ QueryUT ┆ Source  ┆ DeviceI ┆ … ┆ SensorN ┆ SensorT ┆ SensorR ┆ SensorR │
│ adingUTC ┆ C       ┆ ---     ┆ D       ┆   ┆ ame     ┆ ype     ┆ eadingF ┆ eadingR │
│ ---      ┆ ---     ┆ str     ┆ ---     ┆   ┆ ---     ┆ ---     ┆ ---     ┆ h       │
│ i64      ┆ i32     ┆         ┆ str     ┆   ┆ str     ┆ str     ┆ f32     ┆ ---     │
│          ┆         ┆         ┆         ┆   ┆         ┆         ┆         ┆ f32     │
╞══════════╪═════════╪═════════╪═════════╪═══╪═════════╪═════════╪═════════╪═════════╡
│ 17632401 ┆ 1763240 ┆ Conserv ┆ conserv ┆ … ┆ BYCBA_0 ┆ RH      ┆ null    ┆ 45.7400 │
│ 81       ┆ 227     ┆         ┆ :333:c0 ┆   ┆ 3003011 ┆         ┆         ┆ 02      │
│          ┆         ┆         ┆ 08789   ┆   ┆ 1_N___  ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ - RH    ┆         ┆         ┆         │
│ 17632398 ┆ 1763240 ┆ Conserv ┆ conserv ┆ … ┆ BBARCH0 ┆ Tempera ┆ 73.2559 ┆ null    │
│ 78       ┆ 227     ┆         ┆ :333:c0 ┆   ┆ 100001_ ┆ ture    ┆ 97      ┆         │
│          ┆         ┆         ┆ 09072   ┆   ┆ ______  ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ - Tempe ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ ra…     ┆         ┆         ┆         │
│ 17632398 ┆ 1763240 ┆ Conserv ┆ conserv ┆ … ┆ BYCBA_B ┆ RH      ┆ null    ┆ 42.93   │
│ 61       ┆ 227     ┆         ┆ :333:c0 ┆   ┆ 100B06_ ┆         ┆         ┆         │
│          ┆         ┆         ┆ 09063   ┆   ┆ ______  ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ - RH    ┆         ┆         ┆         │
│ 17632395 ┆ 1763240 ┆ Conserv ┆ conserv ┆ … ┆ BYCBA_0 ┆ RH      ┆ null    ┆ 44.8800 │
│ 42       ┆ 227     ┆         ┆ :333:c0 ┆   ┆ 200221_ ┆         ┆         ┆ 01      │
│          ┆         ┆         ┆ 09010   ┆   ┆ E_____  ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ - RH    ┆         ┆         ┆         │
│ 17632395 ┆ 1763240 ┆ Conserv ┆ conserv ┆ … ┆ BYCBA_0 ┆ Tempera ┆ 72.68   ┆ null    │
│ 55       ┆ 227     ┆         ┆ :333:c0 ┆   ┆ 3003010 ┆ ture    ┆         ┆         │
│          ┆         ┆         ┆ 08914   ┆   ┆ 4_S___  ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ - Tempe ┆         ┆         ┆         │
│          ┆         ┆         ┆         ┆   ┆ ra…     ┆         ┆         ┆         │
└──────────┴─────────┴─────────┴─────────┴───┴─────────┴─────────┴─────────┴─────────┘

# 3 Consolidate Readings

At the end of the day, new readings will be consolidated into the table. At the same time, the analytical tables will be generated. 

Analytical tables include:

* `device_readings.parquet`: Sensor readings reorganized to one row per Device and UTC, with measurements across columns vs measurements across rows.* 
* `sensors.parquet`: Information about the unique sensors. Includes information extracted from SensorName. Join this to Sensors during analysis to enhance with Building, Room, Direction, etc.
* `devices.parquet`: Information about unique devices. Includes information extracted from SensorName. 
* `utcs.parquet`: Information related to the UTC times in various datasets. Join to Sensors or Devices to enhance with Date, Time, Year, Hour, Weekday, etc.
* `sensor_readings_daily.parquet`: Example of sensor readings summarized to the daily level which reduces row count by 99.3% for even faster queries.
* `device_readings_daily.parquet`: Example of device readings summarized to the daily level which reduces row count by 99.3% for even faster queries. 

We fully re-generate analytical tables during each consolidation. The data is small enough that this is a fairly quick process, so re-running it in full each time will make it easy to ensure consistency as we expand and change the project.

In [7]:
# To consolidate these into the database, run consolidate_readings.
envdt.consolidate_readings()

# New-readings files are gone now.
# They get deleted each day to confirm that they have been loaded into the database and prepare for the next consolidation.
print(os.listdir('../data/new-readings'))

C:\Users\super\Documents\arbaiza-consulting\environmental-sensor-poc\EnvironmentData.py:1210: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  historical["SensorID"].is_in(sensors["SensorID"]).not_()
C:\Users\super\Documents\arbaiza-consulting\environmental-sensor-poc\EnvironmentData.py:942: DeprecationWarning: `str.concat` is deprecated; use `str.join` instead. Note also that the default `delimiter` for `str.join` is an empty string, not a hyphen.
  polars.col("SensorID").str.concat(", ").alias("Sensors"),
C:\Users\super\Documents\arbaiza-consulting\environmental-sensor-poc\EnvironmentData.py:943: DeprecationWarning: `str.concat` is deprecated; use `str.join` instead. Note also that the default `delimiter` for `str.join` is an empty string, not a hyphen.
  polars.col("SensorName").str.concat(", ").alias("SensorNames"),
C:\Users\super\Documents\arbaiza-consulting\environmental-sensor-poc\EnvironmentData.py:944: DeprecationWarning: `str.concat` is deprecated; use `str.join` instead. Note also that the default `delimiter` for `str.join` is an empty string, not a hyphen.
  polars.col("SensorType").str.concat(", ").alias("SensorTypes")

ColumnNotFoundError: unable to find column "ConservCustomerID"; valid columns: ["SensorReadingUTC", "QueryUTC", "Source", "DeviceID", "DeviceName", "SensorID", "SensorName", "SensorType", "SensorReadingF", "SensorReadingRh", "SensorReadingUTC_SecondsFromPrior"]

Resolved plan until failure:

	---> FAILED HERE RESOLVING 'sink' <---
Parquet SCAN [..\./data//sensor_readings.parquet]
PROJECT */11 COLUMNS

**^^ We want this to be empty** since we have consolidated new readings into the historical data.

Once we are done working with data intake/processing, we close the class to release the file lock on the log file.

In [ ]:
# When done, close the connection to the logs. 
envdt.close()

Let's look at the data we have now:

In [ ]:
# Sensor Readings
# The first rows will be missing the extra fields like HexGatewayMac, etc.
#   I am pulling in some extra fields like DeviceID and DeviceName so we have that by historical. 
#   But some don't make sense to  backfill so they'll be null.
sensor_readings = polars.read_parquet('../data/sensor_readings.parquet')
sensor_readings.head()

In [ ]:
# Recent rows will have the full data, aside from nulls due to a sensor not providing a reading type.
sensor_readings.tail()

In [ ]:
# Device Readings.
device_readings = polars.read_parquet('../data/device_readings.parquet')
device_readings.head()

In [ ]:
# Sensors
sensors = polars.read_parquet('../data/sensors.parquet')
sensors.head()

In [ ]:
# Devices. 
devices = polars.read_parquet('../data/devices.parquet')
devices.head()

In [ ]:
# UTC Date/Time Info
utcs = polars.read_parquet('../data/utcs.parquet').head()
utcs.head()

In [ ]:
# Daily Sensor Readings
# Averages are calculated by summing the "sum" and "row_count" columns and dividing to get the average. 
sensor_readings_daily = polars.read_parquet('../data/sensor_readings_daily.parquet')
sensor_readings_daily.head()

In [ ]:
# Daily Device Readings
# Averages are calculated by summing the "sum" and "row_count" columns and dividing to get the average. 
device_readings_daily = polars.read_parquet('../data/device_readings_daily.parquet')
device_readings_daily.head()

In [ ]:
# Differentiate historical vs. cron readings by filtering on QueryUTC = NULL.
import duckdb
duckdb.sql("""
    SELECT *
    FROM read_parquet('../data/device_readings.parquet') 
    WHERE QueryUTC is null
    LIMIT 5
""").to_df()

Now you are ready to move onto analysis to get human-readable results (not indexed by UTC timestamps). See 2-examples-analysis.ipynb.